version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install node_modules
          command: |
            yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: run tests
          command: yarn test

      - run:
          name: Generate asset files
          command: yarn generate

      - run:
          name: Deploy
          command: yarn run gulp deploy
workflows:
  version: 2
  normal_workflow:
    jobs:
      - build
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 22 * * 0,3"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
